### ISSUE TITLE
demo选择框->提示框(use static data)在IE下有bug

### ISSUE THREAD

**Issue by gumpassion** [dxq613/bui#109]
注意：是在IE浏览器会有问题
demo地址：http://builive.com/demo/select.php#select/suggest2.php
bug说明：有时候无法根据输入来过滤，要多点击几次输入框后，输入过滤才有效果
![image](https://f.cloud.github.com/assets/5291314/2183987/80dbcc84-97b7-11e3-871e-6f099fae7856.png)

**Comment by dxq613** [comment]
focus导致，已经处理
