### ISSUE TITLE
如果导航栏太多怎么办？

### ISSUE THREAD

**Issue by sntetwt** [dxq613/bui#12]
你好！我正在用你们写的插件，感学瞒好用。
但是导航栏到10个，就看不见了，怎么解决这个问题呢？

**Comment by dxq613** [comment]
喔，你是说用的我打包的那个应用么，那上面做了处理，如果超出屏幕分辨率，会在最后一个模块出现下拉的

**Comment by dxq613** [comment]
喔，设计的是出现下拉，这个地方样式有问题，我再fixed一下吧。

**Comment by dxq613** [comment]
http://www.builive.com/apps/default/main.html#detail

将屏幕拖放到最小，只能显示出2个导航，刷新后看看效果。

有可能有缓存，清理一下缓存。
重新下载一下应用，替换掉，assets目录下的文件
