### ISSUE TITLE
折线图

### ISSUE THREAD

**Issue by konghao8013** [dxq613/bui#131]
当前功能
 鼠标移动到折线图 点上显示悬浮框
鼠标移开区域 隐藏悬浮框

求实现新功能
鼠标移动到则线图点上显示悬浮框
鼠标移开区域 隐藏悬浮框

如果鼠标点击折线图值点之后 鼠标移动开区域不隐藏悬浮框
当鼠标再次点击折线图值点之后并移动开区域才隐藏悬浮框

**Comment by fangk** [comment]
这个只能搞成点击里面出现，点击图表外面隐藏。

比较难区分第二次点击是要决定关闭。

**Comment by dxq613** [comment]
http://builive.com/chart/line.php#line/base-click.php
