### ISSUE TITLE
dialog+grid+RowEditing的一个问题

### ISSUE THREAD

**Issue by riwcwt** [dxq613/bui#160]
你好！
        我在dialog(关闭时destroy)中，有一个grid控件，这个grid可以进行行编辑，用的RowEditing。现在问题是，关闭dialog时，在dialog的closing事件中，我执行grid的destroy方法，这样dialog和grid都被drestroy掉了，但是RowEditin没有被destroy掉，也没找到RowEditin的destroy方法。

**Comment by dxq613** [comment]
错误定位，editor.destroy && editor.destroy()写成了，editor.destroy || editor.destroy()，已经修复
