### ISSUE TITLE
增加tree控件

### ISSUE THREAD

**Issue by dxq613** [dxq613/bui#21]
支持的功能：
1. 静态数据支持
2. 动态数据支持
3. 自定义icon
4. 无限级数
5. 增、删、改、查

**Comment by dxq613** [comment]
1. 支持静态数据 完成
2. 自定义icon 实现
3. 连接线
4. 数据异步加载完成
5. 节点增删改查完成
6. 无限级树完成
7. 节点禁用完成
8. 节点配置可勾选完成，提供4种方式
9. 根节点是否显示
10. 多选框完成，支持父节点半选状态

**Comment by foxair** [comment]
支持多选框，单选框，父节点半选状态

**Comment by maxid** [comment]
1. 数据异步加载
2. 拖拽改变排序

**Comment by dxq613** [comment]
待完成功能：
1. Tree Grid 集成
2. Tree Menu 查看
3. 展开折叠的动态效果

是否进行：
1. 单选框是否提供
2. 排序功能，是否页面进行
3. Tree 的编辑功能，是否需要增强
