### ISSUE TITLE
官网关闭了谁还有文档和demo的备份啊？

### ISSUE THREAD

**Issue by woodzeng** [dxq613/bui#232]

**Comment by woodzeng** [comment]
@dxq613 你好，官网停止维护了吗？请问有文档和控件demo库的离线文档吗？

**Comment by guwei4037** [comment]
项目官网打不开了，有demo备份吗？

**Comment by dxq613** [comment]
好像是域名到期没续费，赎回来太贵了。。。

**Comment by dxq613** [comment]
文档都在这里：https://github.com/buiteam/bui-docs

**Comment by dxq613** [comment]
刚升级了个域名：http://www.builive.cn/
