### ISSUE TITLE
有没有考虑加个chart的模块?

### ISSUE THREAD

**Issue by kernnel** [dxq613/bui#25]
bui有没有chart模块？虽然有很多第三方chart库，但是我看的几个都有amd的解决方法（比如high charts），和seajs的写法还是有点区别的，作者有没有考虑自己实现一个chart模块或者集成一个开源chart库啊？

**Comment by dxq613** [comment]
chart是个大坑，很大的坑，暂时没想去做，有很多需要概率、统计的知识，这部分早还给老师了。。。
chart有很多解决方案，不一定非要js的。

**Comment by dxq613** [comment]
基本的
1. Bar chart
2. Line chart
3. Column chart
4. Pie chart
5. Scatter chart
6. Spline chart

复杂的
7. Area chart
8. Combined  charts

**Comment by dxq613** [comment]
全部完成，超额完成
