### ISSUE TITLE
希望bui的标签(tab)能够设置主页

### ISSUE THREAD

**Issue by itomcat666** [dxq613/bui#33]
如题，有时候打开一个页面时需要打开一个默认的tab，将其设置为主页且不可关闭，就是没有右上角的关闭的按钮，希望能实现这个功能，期待新作！

**Comment by dxq613** [comment]
1. 打开默认的tab，已经实现，
2. 不可关闭未添加

**Comment by itomcat666** [comment]
期待楼主能添加这个功能，这个很常用的。

**Comment by dxq613** [comment]
已经添加closeable属性，如果设置closeable ： false，此标签不可关闭
