### ISSUE TITLE
controller.js的destructor方法获取id的代码是一个bug吗?

### ISSUE THREAD

**Issue by softlight0629** [dxq613/bui#40]
destructor: function () {
            var self = this,
                id,
                i,
                view,
                children = self.get('children');
            id = self.get(id);
            for (i = 0; i < children.length; i++) {
                children[i].destroy && children[i].destroy();
            }
            self.get('view').destroy();
            Manager.removeComponent(id);
}

---

id = self.get(id); 是不是应该为 id = self.get('id');

**Comment by dxq613** [comment]
thanks ,
调用destroy的情形太少，所以这个问题没有暴露出来。
已经处理
