### ISSUE TITLE
Grid 新的插件

### ISSUE THREAD

**Issue by dxq613** [dxq613/bui#41]
提出有关grid的新功能，我根据需求的多少和复杂程度安排优先级实现

**Comment by kernnel** [comment]
需要类似的过滤功能
![image](https://f.cloud.github.com/assets/1452833/990971/e41ac138-094b-11e3-9d6c-9376938c0ad7.png)

当然如果能做成这样就更好
![image](https://f.cloud.github.com/assets/1452833/990981/820bd508-094c-11e3-9264-438bf4309974.png)

**Comment by dxq613** [comment]
表头拖拽宽度功能，或者设置一个max-width，点击列的间隙时，变成max-width

**Comment by gumpassion** [comment]
表格的编辑目前有一种是弹出对话框来编辑。希望增加一种插件，点击表格的编辑时，在记录的下方新增一行，内容是该行记录的编辑输入框、保存按钮、取消按钮。该应用场景为行编辑时，一行放不下所有的字段。

**Comment by VicJ** [comment]
表格编辑后，验证不符合条件时，失焦后，能不能立即在单元格上显示验证结果，并保留错误数据；
现在的做法是回退到上一次正确的结果，然后必须通过独立的功能触发验证方法。

**Comment by dxq613** [comment]
目前的表格编辑是实时进行校验，再输入的时候已经进行了校验，所以失焦时回滚到没多大问题，不过可以考虑增加一种校验失败不回滚的配置方式，不过此种情况下，这一列的其他单元格无法进行编辑了。
