### ISSUE TITLE
关于Alert和Dialog的层级显示问题

### ISSUE THREAD

**Issue by jefth** [dxq613/bui#50]
代码片段如下：
BUI.use(['bui/overlay'], function (Overlay) {
            $('.j_testalert').on('click', function (e) {
                var dialog = new Overlay.Dialog({
                    title: '窗口',
                    width: 400,
                    height: 300,
                    bodyContent: '1.先点击A按钮，“确定”后显示alert.“确定”.“关闭”A<br />2.然后再点击B按钮，“确定”，但是alert在dialog层下面了。',
                });
                dialog.show();
                BUI.Message.Alert('测试弹出显示层级,第2次弹出会在dialog之下', 'info');
            });
        });

--------------------我是分割线-------------------
先按A，再按B，，alert就在dialog下面了。。。求解决配置，求修正~~~

**Comment by dxq613** [comment]
因为dialog和message是同一个z-index,可以配置dilaog的zIndex属性，默认为1070，可以小于1070

var dialog = new Overlay.Dialog({
title: '窗口',
width: 400,
height: 300,
zIndex : 1069,
bodyContent: '1.先点击A按钮，“确定”后显示alert.“确定”.“关闭”A
2.然后再点击B按钮，“确定”，但是alert在dialog层下面了。',
});

**Comment by dxq613** [comment]
message的z-index已经调整到1300
