### ISSUE TITLE
bui后台系统，当打开多个标签，再切回之前的标签，滚动鼠标滑轮，右侧浏览器滚动条不动

### ISSUE THREAD

**Issue by shuanys** [dxq613/bui#56]
bui后台系统，当打开多个标签，再切回之前的标签，滚动鼠标滑轮，右侧浏览器滚动条不动， http://builive.com/apps/default/main.html#menu/dyna-menu中测试的，浏览器为chrome Version 30.0.1599.69 m

**Comment by dxq613** [comment]
布局的css导致存在多出像素的存在，使得滚动失效，已解决
