### ISSUE TITLE
提交两个BUG

### ISSUE THREAD

**Issue by zqjimlove** [dxq613/bui#61]
## bui/extensions/treepicker

当使用异步加载时,如果存在默认值的话会出现_Uncaught TypeError: Cannot read property 'parent' of null_ 的错误，导致treepicker无法正常展开栏目。
### 原因：

因为设置了默认值，但是treepicker属于异步加载，所以这个节点和他的父节点都还未加载。
### 临时解决方案：

默认值的文本域和treepicker的文本域分开，选择后通过调用事件设置值。
## bui/tree

当disable某节点时，会出现checkbox。
### 原因：

源码中清除状态时将“checked”属性设置为false，并且判断是否开启checkbox仅用 checked 属性是否存在作为判定条件。
### 临时解决方案：

```
tree.setItemStatus(node, "disabled", true);
node['checked'] = null;
```

**Comment by dxq613** [comment]
第二个已经解决，第一个异步加载的树获取不到值对应的文本，暂时无法解决

**Comment by safecat** [comment]
关于“异步加载的树获取不到值对应的文本”，我最近在使用select2这个控件，这个控件在载入时如果检测到有预设值，会向服务器请求该值对应的文本，我觉得这也算一个解决方案，至少基本的操作界面逻辑是完整的。
