### ISSUE TITLE
Select及Picker赋值的bug

### ISSUE THREAD

**Issue by cloudswindow** [dxq613/bui#67]
比如：期望让select默认选择第一项
<input type="hidden" id="orderDirection" value="0" name="orderDirection" />

 bui  源码中：
![3 hhza6aqlts 3qc9h32 lo](https://f.cloud.github.com/assets/813633/1599277/3ce03032-5352-11e3-8d10-e1a7e91cff84.jpg)

直接读取了input的value，传递给Picker的setSelectedValue方法 ，这里直接从input中获取的值，如果input的value是个数字，则得到的是数字。

![7h_w3mn0 fv40xouxc 4g](https://f.cloud.github.com/assets/813633/1599281/6e3a5c2a-5352-11e3-88c6-ea831c87e27f.jpg)

而在这里，可以看到有个if(v)的判断，如果刚刚在input里设置了数字0，那么在select里拿到的value是个数字0，调用picker的selectSelectedValue里，if一下就是非了，直接跳过。。。。因此通过valueField 设置初始值有点坑啊，第一项是完全不可能设置的。

建议还是不强制用字符串作为Picker的赋值函数参数吧，0 是完全有可能作为key的

**Comment by dxq613** [comment]
已经处理
