### ISSUE TITLE
Grid 扩展行排序时明细不隐藏的bug

### ISSUE THREAD

**Issue by cloudswindow** [dxq613/bui#70]
小自在天  17:51:52
@js-dxq 表格行明细扩展有bug啊，展开之后排序，子项全部跑上面去了  
![tgu hkt g99dh ojl3ttk](https://f.cloud.github.com/assets/813633/1630358/1a637fc2-574a-11e3-9551-c9a4c51ff93a.jpg)

小自在天  17:52:04

小自在天  17:52:11
demo页面也有这个问题
![9sgxedqq 9f1l kyj1kq7](https://f.cloud.github.com/assets/813633/1630362/1e9d3290-574a-11e3-86bf-4410e681f027.jpg)

**Comment by dxq613** [comment]
本来的方式是排序时重新生成所有的行，此BUG不存在，但是后面有人提出要实现页面上直接排序，不重新声称能够所有的行，所以这时候排序就出现问题了，考虑加个参数控制一下

**Comment by dxq613** [comment]
增加frontSortable 属性，默认关闭直接使用DOM排序，排序时会重新生成DOM
