### ISSUE TITLE
Layout的一些bug

### ISSUE THREAD

**Issue by dxq613** [dxq613/bui#91]
### 问题
1. 折叠布局，展开折叠时未重置子控件的宽高
2. 绝对布局未注册
3. 表格布局，内部元素的宽高自适应存在问题

**Comment by shirokumacafe** [comment]
1.accordion点击折叠栏，动画中，点击其他的折叠栏会造成accordion的折叠显示混乱。
2.将浏览器拉伸致一个较矮的高度，accordion的内容显示异常。
![qq20131227151144](https://f.cloud.github.com/assets/2555220/1813594/4577911a-6ec6-11e3-91f2-38b62ccd9497.jpg)

**Comment by dxq613** [comment]
1. 已经处理
2. 已经处理
3. 无法处理，需要挨个处理其中的高度问题

**Comment by dxq613** [comment]
1. table 布局提供一个固定列宽，行高的模式
2. 不定宽度时计算平均宽度作为宽高，动态自适应

**Comment by shirokumacafe** [comment]
1.在tab里面显示一个grid的组件会有样式bug
![qq20140102143713](https://f.cloud.github.com/assets/2555220/1831077/816a3450-7378-11e3-9852-033feacf504e.jpg)

在grid里用鼠标左键拖拽下拉，或者缩小浏览器的大小后都会出现该问题
![qq20140102143718](https://f.cloud.github.com/assets/2555220/1831078/819c0ff2-7378-11e3-8f4e-ab1bee1af295.jpg)

2.更新到最新的bui后layout出现问题，已确认清空缓存
![qq20140102144043](https://f.cloud.github.com/assets/2555220/1831083/e269f9c0-7378-11e3-96f2-c0375f18f621.jpg)
