### ISSUE TITLE
关闭“搜索页面示例“的tab页面时，出错

### ISSUE THREAD

**Issue by howgoo** [dxq613/bui#98]
http://www.builive.com/apps/default/main.html#search/example

关闭“搜索页面示例“的tab页面时，出错。
bui-min.js (第 5 行)
TypeError: e.get(...) is undefined
...earLocalFilter()},processLoad:function(e,t){var n=this,r=n.get("hasErrorProperty...

![qq20140108163029](https://f.cloud.github.com/assets/283002/1866845/6f1065ba-783f-11e3-9ab9-23ea53b39e51.jpg)
![qq20140108163051](https://f.cloud.github.com/assets/283002/1866852/ab7ac69e-783f-11e3-9c69-45a541d01ac2.jpg)

**Comment by dxq613** [comment]
防止控件反复destroy
